# Generated by Django 6.0.5 on 2026-05-10 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='temps_lecture',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
